version: '3.8'

services:
  db:
    image: mrtncalderon9/db:1.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project-docker
    ports:
      - "3307:3306"  

  backend:
    image: mrtncalderon9/backend:1.0
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/project-docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "9000:9000"
    depends_on:
      - db

  front:
    image: mrtncalderon9/frontend:1.0
    container_name: fronted-container
    ports:
      - "8080:80"
    depends_on:
      - backend